# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"\x1b\n\rMemberRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"?\n\x0bMemberReply\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x62irthday\x18\x02 \x01(\t\x12\x10\n\x08province\x18\x03 \x01(\t27\n\nBTSService\x12)\n\tGetMember\x12\x0e.MemberRequest\x1a\x0c.MemberReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEMBERREQUEST']._serialized_start=14
  _globals['_MEMBERREQUEST']._serialized_end=41
  _globals['_MEMBERREPLY']._serialized_start=43
  _globals['_MEMBERREPLY']._serialized_end=106
  _globals['_BTSSERVICE']._serialized_start=108
  _globals['_BTSSERVICE']._serialized_end=163
# @@protoc_insertion_point(module_scope)
